### ISSUE TITLE
在Ubuntu环境下使用不支持方向键

### ISSUE THREAD

**Issue by 185264646** [apachecn/CDNDrive#11]
按下方向键后出现类似 `^[[A` 的字符串，环境为WSL Ubuntu 20.04。已经安装python3-readlike，并且经验证在python3.8默认的交互界面下可以支持方向键。作为对比，直接使用Windows平台下的Python3则可以支持方向键。

**Comment by jiangzhonglian** [comment]
这是系统问题，和这个软件没什么关系

**Comment by 185264646** [comment]
> 这是系统问题，和这个软件没什么关系

可是只有在使用该软件的时候才会出现这种情况啊，使用python3本身的交互界面的时候方向键可以很好的工作诶。不止Ubuntu，termux上也是一样的情况。

**Comment by 185264646** [comment]
并不是系统的问题，应当在代码最前面加上`import readline`并且用pip安装readline包才能让input()函数支持方向键。

**Comment by wizardforcel** [comment]
好的。交互模式将在下个版本中移除。
