### ISSUE TITLE
macos 10.15 安装出错

### ISSUE THREAD

**Issue by rawbin-** [apachecn/CDNDrive#12]
pip install CDNDrive
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not find a version that satisfies the requirement CDNDrive (from versions: none)
ERROR: No matching distribution found for CDNDrive

**Comment by wizardforcel** [comment]
我们的所有项目都不考虑兼容 Python2，请尽快升级到 Python3
