### ISSUE TITLE
bili登录失败

### ISSUE THREAD

**Issue by saraikisaki** [apachecn/CDNDrive#8]
登录失败：Expecting value: line 1 column 1 (char 0)

**Comment by saraikisaki** [comment]
不是这个就是_登录失败：服务繁忙, 请稍后再试_需要什么网络条件吗

**Comment by yllhwa** [comment]
可以用cookies登陆Sent from my Huawei phone-------- Original message --------From: saraikisaki <notifications@github.com>Date: Mon, Aug 31, 2020, 23:49To: apachecn/CDNDrive <CDNDrive@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [apachecn/CDNDrive] bili登录失败 (#8)

不是这个就是_登录失败：服务繁忙, 请稍后再试_需要什么网络条件吗

**Comment by wizardforcel** [comment]
可能是 @Hsury 的验证码识别挂了，先用 cookie 登录吧。

**Comment by 185264646** [comment]
> 不是这个就是
> _登录失败：服务繁忙, 请稍后再试_
> 需要什么网络条件吗

这样用：`cdrive cookies bili SESSDATA=xxxxx` 其中的xxxxx要自行在浏览器端登录后获取，方法是登录后在任意bilibili.com域名内网站用开发者人员工具等获取SESSDATA的值。

**Comment by zsbai** [comment]
> > 不是这个就是
> > _登录失败：服务繁忙, 请稍后再试_
> > 需要什么网络条件吗
> 
> 这样用：`cdrive cookies bili SESSDATA=xxxxx` 其中的xxxxx要自行在浏览器端登录后获取，方法是登录后在任意bilibili.com域名内网站用开发者人员工具等获取SESSDATA的值。

cookie登陆出现 用户信息获取失败 ，用的是你说的格式
